# Generated by Django 4.1.7 on 2023-03-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='message',
            field=models.TextField(),
        ),
    ]
